export const data = [
    {
        category:'Living Room',
        sub: 'Sofa',
        name: "Novogratz Brittany 81.5'' Round Arm Sleeper",
        price: '84,000',
        discount: '15',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Est atque non optio nihil, eaque dolor neque in quaerat enim autem dolores, soluta debitis amet, natus iusto? Odit et veritatis quidem maxime, consequuntur accusamus ad nesciunt pariatur officia quaerat? Officia nostrum expedita facere fugiat! Laboriosam velit nam inventore minus. Eos iure suscipit asperiores corrupti numquam repellendus porro minus consequatur iusto dolorem.',
        wishList: false,
        id: 1,
        topSelling: true,
        image: 'https://i.pinimg.com/originals/be/77/e4/be77e4d4e7492ee3aa17e5a7c69fae31.jpg'
    },
    {
        category:'Living Room',
        sub: 'Sofa',
        name: "Winnie 74'' Velvet Round Arm Sofa",
        price: '73,000',
        discount: '13',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Est atque non optio nihil, eaque dolor neque in quaerat enim autem dolores, soluta debitis amet, natus iusto? Odit et veritatis quidem maxime, consequuntur accusamus ad nesciunt pariatur officia quaerat? Officia nostrum expedita facere fugiat! Laboriosam velit nam inventore minus. Eos iure suscipit asperiores corrupti numquam repellendus porro minus consequatur iusto dolorem.',
        wishList: false,
        id: 2,
        image: 'http://sc04.alicdn.com/kf/H919ed8e8d2444c4a8997114f35f743d1k.jpg'
    },
    {
        id: 3,
        category:'Living Room',
        sub: 'Sofa',
        name: "Garren 75.6'' Square Arm Sofa",
        price: '73,000',
        discount: '13',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Est atque non optio nihil, eaque dolor neque in quaerat enim autem dolores, soluta debitis amet, natus iusto? Odit et veritatis quidem maxime, consequuntur accusamus ad nesciunt pariatur officia quaerat? Officia nostrum expedita facere fugiat! Laboriosam velit nam inventore minus. Eos iure suscipit asperiores corrupti numquam repellendus porro minus consequatur iusto dolorem.',
        wishList: false,
        topSelling: true,
        image: 'https://media.jumiadeals.com/ng_live/b00a836a0260b58f095ded4.desktop-gallery-large.jpg'
    },
    {
        id: 4,
        category:'Living Room',
        sub: 'Console Tables',
        name: "Bletherston 48'' Solid Wood Console Table",
        price: '43,000',
        discount: '18',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Est atque non optio nihil, eaque dolor neque in quaerat enim autem dolores, soluta debitis amet, natus iusto? Odit et veritatis quidem maxime, consequuntur accusamus ad nesciunt pariatur officia quaerat? Officia nostrum expedita facere fugiat! Laboriosam velit nam inventore minus. Eos iure suscipit asperiores corrupti numquam repellendus porro minus consequatur iusto dolorem.',
        wishList: false,
        image: 'https://secure.img1-fg.wfcdn.com/im/83687207/resize-h310-w310%5Ecompr-r85/2973/29732018/Foshee+28.25%27%27+Console+Table.jpg'
    },
    {
        id: 5,
        category:'Living Room',
        sub: 'Console Tables',
        name: "Arsenault 46'' Console Table",
        price: '58,000',
        discount: '27',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Est atque non optio nihil, eaque dolor neque in quaerat enim autem dolores, soluta debitis amet, natus iusto? Odit et veritatis quidem maxime, consequuntur accusamus ad nesciunt pariatur officia quaerat? Officia nostrum expedita facere fugiat! Laboriosam velit nam inventore minus. Eos iure suscipit asperiores corrupti numquam repellendus porro minus consequatur iusto dolorem.',
        wishList: false,
        image: 'https://secure.img1-fg.wfcdn.com/im/12648294/resize-h310-w310%5Ecompr-r85/7724/77244957/Arsenault+46%27%27+Console+Table.jpg'
    },
    {
        id: 6,
        category:'Living Room',
        sub: 'Console Tables',
        name: "Darrion 42'' Console Table",
        price: '46,000',
        discount: '22',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Est atque non optio nihil, eaque dolor neque in quaerat enim autem dolores, soluta debitis amet, natus iusto? Odit et veritatis quidem maxime, consequuntur accusamus ad nesciunt pariatur officia quaerat? Officia nostrum expedita facere fugiat! Laboriosam velit nam inventore minus. Eos iure suscipit asperiores corrupti numquam repellendus porro minus consequatur iusto dolorem.',
        wishList: false,
        image: 'https://secure.img1-fg.wfcdn.com/im/99976558/resize-h310-w310%5Ecompr-r85/1109/110954926/Darrion+42%27%27+Console+Table.jpg'
    },
    {
        id: 7,
        category:'Living Room',
        sub: 'Console Tables',
        name: "Huxley 39.4'' Console Table",
        price: '54,000',
        discount: '28',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Est atque non optio nihil, eaque dolor neque in quaerat enim autem dolores, soluta debitis amet, natus iusto? Odit et veritatis quidem maxime, consequuntur accusamus ad nesciunt pariatur officia quaerat? Officia nostrum expedita facere fugiat! Laboriosam velit nam inventore minus. Eos iure suscipit asperiores corrupti numquam repellendus porro minus consequatur iusto dolorem.',
        wishList: false,
        topSelling: true,
        image: 'https://secure.img1-fg.wfcdn.com/im/83305553/resize-h310-w310%5Ecompr-r85/1200/120050972/Huxley+39.4%27%27+Console+Table.jpg'
    },
    {
        id: 8,
        category:'Living Room',
        sub: 'TV Stands & Entertainment Centers',
        name: "Millen TV Stand for TVs up to 60",
        price: '72,000',
        discount: '12',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Est atque non optio nihil, eaque dolor neque in quaerat enim autem dolores, soluta debitis amet, natus iusto? Odit et veritatis quidem maxime, consequuntur accusamus ad nesciunt pariatur officia quaerat? Officia nostrum expedita facere fugiat! Laboriosam velit nam inventore minus. Eos iure suscipit asperiores corrupti numquam repellendus porro minus consequatur iusto dolorem.',
        wishList: false,
        topSelling: true,
        image: 'https://secure.img1-fg.wfcdn.com/im/84902450/resize-h310-w310%5Ecompr-r85/1379/137921914/Millen+TV+Stand+for+TVs+up+to+60%22.jpg'
    },
    {
        id: 9,
        category:'Living Room',
        sub: 'TV Stands & Entertainment Centers',
        name: "Wolla TV Stand for TVs up to 65",
        price: '90,000',
        discount: '15',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Est atque non optio nihil, eaque dolor neque in quaerat enim autem dolores, soluta debitis amet, natus iusto? Odit et veritatis quidem maxime, consequuntur accusamus ad nesciunt pariatur officia quaerat? Officia nostrum expedita facere fugiat! Laboriosam velit nam inventore minus. Eos iure suscipit asperiores corrupti numquam repellendus porro minus consequatur iusto dolorem.',
        wishList: false,
        image: 'https://secure.img1-fg.wfcdn.com/im/89790983/resize-h310-w310%5Ecompr-r85/1468/146889026/Wolla+TV+Stand+for+TVs+up+to+65%22.jpg'
    },
    {
        id: 10,
        category:'Living Room',
        sub: 'TV Stands & Entertainment Centers',
        name: "Bradwell TV Stand for TVs up to 60",
        price: '65,000',
        discount: '13',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Est atque non optio nihil, eaque dolor neque in quaerat enim autem dolores, soluta debitis amet, natus iusto? Odit et veritatis quidem maxime, consequuntur accusamus ad nesciunt pariatur officia quaerat? Officia nostrum expedita facere fugiat! Laboriosam velit nam inventore minus. Eos iure suscipit asperiores corrupti numquam repellendus porro minus consequatur iusto dolorem.',
        wishList: false,
        image: 'https://secure.img1-fg.wfcdn.com/im/75414010/resize-h310-w310%5Ecompr-r85/5108/51086968/Bradwell+TV+Stand+for+TVs+up+to+60%22.jpg'
    },
    {
        id: 11,
        category:'Living Room',
        sub: 'TV Stands & Entertainment Centers',
        name: "Oglethorpe TV Stand for TVs up to 49",
        price: '55,000',
        discount: '17',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Est atque non optio nihil, eaque dolor neque in quaerat enim autem dolores, soluta debitis amet, natus iusto? Odit et veritatis quidem maxime, consequuntur accusamus ad nesciunt pariatur officia quaerat? Officia nostrum expedita facere fugiat! Laboriosam velit nam inventore minus. Eos iure suscipit asperiores corrupti numquam repellendus porro minus consequatur iusto dolorem.',
        wishList: false,
        topSelling: true,
        image: 'https://secure.img1-fg.wfcdn.com/im/48386738/resize-h310-w310%5Ecompr-r85/1082/108269016/Oglethorpe+TV+Stand+for+TVs+up+to+49%22.jpg'
    },
]